
# Use the official Node.js image as the base image
FROM node:14-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install --production

# Copy the dist folder to the working directory
COPY dist ./dist

# Expose the port that your application listens on
EXPOSE 3000

# Start the application
CMD ["node", "dist/index.js"]
