version: '3'
services:
  app:
    image: coupon-scraping-app:1.0.0
    container_name: coupon-scraping-app
    depends_on:
      - postgres
    environment:
      - APP_PORT=80
      - AUTH_SECRET=c29tZXRpbWViZWd1bnN5bGxhYmxlcG9ldGFzbGVlcHA=
      - DATABASE_URL=postgresql://user:password@postgres:5432/db?schema=public
    networks:
      - intra-domain
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - intra-domain
networks:
  intra-domain:
    driver: bridge
  nginx-network:
    external: true
